projeto/core/urls.py
from django.urls import path
from projeto.core import views as v

app_name = 'core'

urlpatterns = [
	path('', v.index, name='index'),
	
]

projeto/estoque/urls.py
from django.urls import path
from projeto.estoque import views as v

app_name = "estoque"

urlpatterns = [
	path('entrada/', v.estoque_entrada_list, name="estoque_entrada_list"),
	path('entrada/<int:pk>/', v.estoque_entrada_detail, name="estoque_entrada_detail"),
	path('entrada/add/', v.estoque_entrada_add, name="estoque_entrada_add"),
	# path('<int:pk>/edit/', v.EstoqueUpdate.as_view(), name="estoque_update"),
	# path('add/', v.EstoqueCreate.as_view(), name="estoque_add"),

	path('saida/', v.estoque_saida_list, name="estoque_saida_list"),
	path('saida/<int:pk>/', v.estoque_saida_detail, name="estoque_saida_detail"),
	path('saida/add/', v.estoque_saida_add, name="estoque_saida_add"),
]

projeto/produto/urls.py
from django.urls import path
from projeto.produto import views as v

app_name = "produto"

urlpatterns = [
	path('', v.produto_list, name="produto_list"),
	path('<int:pk>/', v.produto_detail, name="produto_detail"),
	path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name="produto_update"),
	path('<int:pk>/json/', v.produto_json, name="produto_json"),
	path('add/', v.ProdutoCreate.as_view(), name="produto_add"),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('admin/', admin.site.urls),
]

projeto/core/models.py
from django.db import models

# Create your models here.

class TimeStampedModel(models.Model):
	created = models.DateTimeField(
			'criado em',
			auto_now_add=True,
			auto_now=False
		)

	modified = models.DateTimeField(
			'modificado em',
			auto_now_add=False,
			auto_now=True
		)

	class Meta:
		# Usar classe como herança de classe em outros Models
		abstract = True

projeto/core/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
	return render(request, 'index.html')

projeto/core/templates/includes/nav.html
<!-- navbar navbar-light bg-light static-top -->
    <nav class="bg-light site-header sticky-top py-1">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="{% url 'core:index' %}">
          Estoque
        </a>

        <a class="py-2 d-none d-md-inline-block" href="{% url 'produto:produto_list' %}">Lista de Produtos</a>
  
        <li class="py-2 d-none d-md-inline-block nav-item-dropdown" >
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspoup="true" aria-expanded="false"> Estoque</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}"><i class="fa fa-arrow-up estoque-ok"></i> Entrada</a>
            <a class="dropdown-item" href="{% url 'estoque:estoque_saida_list' %}"><i class="fa fa-arrow-down estoque-nok"></i> Saída</a>
          </div>
        </li>


      </div>
    </nav>